name: Teleblock
author: Dreadedfall
main: io.github.dreadedfall.teleblock.Teleblock
version: 1.2.1
description: Teleports the player to a random location when on a specific type of block saying a specific word. The block and word are specified in the config.yml as strings.
